<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%pages}}`.
 */
class m200822_155452_create_pages_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%pages}}', [
            'id' => $this->primaryKey(),
            'name' => $this->string()->notNull(),
            'alias' => $this->string()->unique(),
            'type' => $this->string()->notNull()->defaultValue('_link'),
            'parent_id' => $this->integer()->null(),
            'order_sort' => $this->integer()->null(),
            'deleted' => $this->boolean()->defaultValue(0),
            'allow_delete' => $this->boolean()->defaultValue(0),
            'allow_parent' => $this->boolean()->defaultValue(0),
            'created_at' => $this->dateTime(),
            'updated_at' => $this->dateTime(),
        ]);

        $this->addForeignKey('fk-page_parent_id', '{{%pages}}', 'parent_id', '{{%pages}}', 'id');

        $this->batchInsert('{{%pages}}', ['name', 'alias', 'type', 'parent_id', 'order_sort', 'allow_delete', 'allow_parent'], [
            [
                'name' => 'Home',
                'alias' => '/',
                'type' => '_link',
                'parent_id' => null,
                'order_sort' => 0,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Services',
                'alias' => null,
                'type' => '_text',
                'parent_id' => null,
                'order_sort' => 1,
                'allow_delete' => 0,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Industries',
                'alias' => null,
                'type' => '_text',
                'parent_id' => null,
                'order_sort' => 2,
                'allow_delete' => 0,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Languages',
                'alias' => null,
                'type' => '_text',
                'parent_id' => null,
                'order_sort' => 3,
                'allow_delete' => 0,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Company',
                'alias' => null,
                'type' => '_text',
                'parent_id' => null,
                'order_sort' => 4,
                'allow_delete' => 0,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Blog',
                'alias' => '/blog',
                'type' => '_link',
                'parent_id' => null,
                'order_sort' => 5,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Contact Us',
                'alias' => null,
                'type' => '_text',
                'parent_id' => null,
                'order_sort' => 6,
                'allow_delete' => 0,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Rent Equipment',
                'alias' => '/rent-equipment',
                'type' => '_link',
                'parent_id' => null,
                'order_sort' => 7,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],

            // Services
            [
                'name' => 'Translation services',
                'alias' => null,
                'type' => '_text',
                'parent_id' => 2,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Certified translation',
                'alias' => null,
                'type' => '_text',
                'parent_id' => 2,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Transcription Services',
                'alias' => null,
                'type' => '_text',
                'parent_id' => 2,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Interpreting Services',
                'alias' => null,
                'type' => '_text',
                'parent_id' => 2,
                'order_sort' => 3,
                'allow_delete' => 1,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Localization',
                'alias' => null,
                'type' => '_text',
                'parent_id' => 2,
                'order_sort' => 4,
                'allow_delete' => 1,
                'allow_parent' => 1,
            ],
            [
                'name' => 'Business Event Planing',
                'alias' => '/business-event-planing',
                'type' => '_link',
                'parent_id' => 2,
                'order_sort' => 5,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Legal Translation Services',
                'alias' => '/legal-translation-services',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Medical Translations',
                'alias' => '/medical-translations',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Finance',
                'alias' => '/finance',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Immigration Services',
                'alias' => '/immigration-services',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 3,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Technical & Scientific',
                'alias' => '/Technical-and-scientific',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 4,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'IT Translations',
                'alias' => '/it-translations',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 5,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Business Translation',
                'alias' => '/business-translation',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 6,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Marketing Translation',
                'alias' => '/marketing-translation',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 7,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Website Translation',
                'alias' => '/website-translation',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 8,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Document Translation',
                'alias' => '/document-translation',
                'type' => '_link',
                'parent_id' => 9,
                'order_sort' => 8,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Certified Translation',
                'alias' => '/certified-translation',
                'type' => '_link',
                'parent_id' => 10,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Notarized translations',
                'alias' => '/notarized-translation',
                'type' => '_link',
                'parent_id' => 10,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Apostille',
                'alias' => '/apostille',
                'type' => '_link',
                'parent_id' => 10,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Video Transcription Services',
                'alias' => '/video-transcription-services',
                'type' => '_link',
                'parent_id' => 11,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Audio Transcription Services',
                'alias' => '/audio-transcription-services',
                'type' => '_link',
                'parent_id' => 11,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Interviews Transcription Services',
                'alias' => '/interviews-transcription-services',
                'type' => '_link',
                'parent_id' => 11,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Other Transcription',
                'alias' => '/other-transcription',
                'type' => '_link',
                'parent_id' => 11,
                'order_sort' => 3,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Simultaneous Translation',
                'alias' => '/simultaneous-translation',
                'type' => '_link',
                'parent_id' => 12,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Consecutive Translation',
                'alias' => '/consecutive-translation',
                'type' => '_link',
                'parent_id' => 12,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'In-Person Interpreting Services',
                'alias' => '/in-person-interpreting-services',
                'type' => '_link',
                'parent_id' => 12,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Over The Phone',
                'alias' => '/over-the-phone',
                'type' => '_link',
                'parent_id' => 12,
                'order_sort' => 3,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Conference Interpreting',
                'alias' => '/conference-interpreting',
                'type' => '_link',
                'parent_id' => 12,
                'order_sort' => 4,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Websites',
                'alias' => '/websites',
                'type' => '_link',
                'parent_id' => 13,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Software',
                'alias' => '/software',
                'type' => '_link',
                'parent_id' => 13,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'App Localization',
                'alias' => '/app-localization',
                'type' => '_link',
                'parent_id' => 13,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Legal',
                'alias' => '/legal',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Banking and Finance',
                'alias' => '/banking-and-finance',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Medical',
                'alias' => '/medical',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Business',
                'alias' => '/business',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 3,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Tourism',
                'alias' => '/tourism',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 4,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Marketing',
                'alias' => '/marketing',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 5,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Technology',
                'alias' => '/technology',
                'type' => '_link',
                'parent_id' => 3,
                'order_sort' => 6,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Armenian',
                'alias' => '/armenian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 0,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Arabic',
                'alias' => '/arabic',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 1,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Bulgarian',
                'alias' => '/bulgarian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 2,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Chinese',
                'alias' => '/chinese',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 3,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Czech',
                'alias' => '/czech',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 4,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'English',
                'alias' => '/english',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 5,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'French',
                'alias' => '/french',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 6,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Georgian',
                'alias' => '/georgian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 7,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'German',
                'alias' => '/german',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 8,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Greek',
                'alias' => '/greek',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 9,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Indian',
                'alias' => '/indian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 10,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Italian',
                'alias' => '/italian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 11,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Japanese',
                'alias' => '/japanese',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 12,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Lithuanian',
                'alias' => '/lithuanian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 13,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Dutch',
                'alias' => '/dutch',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 14,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Polish',
                'alias' => '/polish',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 15,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Portuguese',
                'alias' => '/portuguese',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 16,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Romanian',
                'alias' => '/romanian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 17,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Russian',
                'alias' => '/russian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 18,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Korean',
                'alias' => '/korean',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 19,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Spanish',
                'alias' => '/spanish',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 20,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Ukrainian',
                'alias' => '/ukrainian',
                'type' => '_text',
                'parent_id' => 4,
                'order_sort' => 21,
                'allow_delete' => 1,
                'allow_parent' => 0,
            ],

            [
                'name' => 'About Us',
                'alias' => '/about-us',
                'type' => '_link',
                'parent_id' => 5,
                'order_sort' => 0,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Credentials',
                'alias' => '/credentials',
                'type' => '_link',
                'parent_id' => 5,
                'order_sort' => 1,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Customers',
                'alias' => '/customers',
                'type' => '_link',
                'parent_id' => 5,
                'order_sort' => 2,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],

            [
                'name' => 'Get In Touch',
                'alias' => '/get-in-touch',
                'type' => '_link',
                'parent_id' => 7,
                'order_sort' => 0,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Help Us Improve',
                'alias' => '/help-us-improve',
                'type' => '_link',
                'parent_id' => 7,
                'order_sort' => 1,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'FAQs',
                'alias' => '/faqs',
                'type' => '_link',
                'parent_id' => 7,
                'order_sort' => 2,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
            [
                'name' => 'Join Us',
                'alias' => '/join-us',
                'type' => '_link',
                'parent_id' => 7,
                'order_sort' => 3,
                'allow_delete' => 0,
                'allow_parent' => 0,
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%pages}}');
        $this->dropForeignKey('fk-page_parent_id', '{{%pages}}');
    }
}
